name: Example

on:
  push:
    branches: [main]

jobs:
  mod-ts-and-relative-import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: ./test-edge-functions.sh
